# Generated by Django 3.2.3 on 2021-05-31 02:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('estruturaEscolar', models.FloatField(default=0)),
                ('qualidadeEscolar', models.FloatField(default=0)),
                ('segurancaEscolar', models.FloatField(default=0)),
                ('alimentacaoEscolar', models.FloatField(default=0)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=datetime.datetime(2021, 5, 31, 2, 44, 1, 675288, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataNascimento', models.DateField(default=datetime.datetime(2021, 5, 31, 2, 44, 1, 673294, tzinfo=utc))),
                ('dataCadastro', models.DateField(default=datetime.datetime(2021, 5, 31, 2, 44, 1, 673294, tzinfo=utc))),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('escolaAtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escola')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuário', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField(default=datetime.datetime(2021, 5, 31, 2, 44, 1, 674292, tzinfo=utc))),
                ('estruturaEscolar', models.IntegerField(default=0)),
                ('qualidadeEscolar', models.IntegerField(default=0)),
                ('segurancaEscolar', models.IntegerField(default=0)),
                ('alimentacaoEscolar', models.IntegerField(default=0)),
                ('comentario', models.CharField(max_length=256)),
                ('rankingDaAvaliacao', models.FloatField(default=1)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('escolaAvaliada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escola')),
            ],
        ),
    ]
