# Generated by Django 3.2.3 on 2021-06-15 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='descricao',
            field=models.CharField(default='texto', max_length=4096),
        ),
        migrations.AddField(
            model_name='escola',
            name='ensinoFundamental',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='ensinoMedio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='foto',
            field=models.CharField(default='http', max_length=2048),
        ),
        migrations.AddField(
            model_name='escola',
            name='preAlfa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='site',
            field=models.CharField(default='http', max_length=2048),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='ano',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 2, 41, 50, 79418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hora',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 2, 41, 50, 79938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataCadastro',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 2, 41, 50, 78954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dataNascimento',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 2, 41, 50, 78932, tzinfo=utc)),
        ),
    ]
